schemaVersion: 2.1.0
metadata:
  name: extension crash
components:
  - name: python
    container:
      image: quay.io/devspaces/udi-rhel9
      env:
        - name: VSCODE_DEFAULT_WORKSPACE
          value: .
commands:
  - id: create-environment
    exec:
      component: python
      workingDir: ${PROJECT_SOURCE}
      commandLine: |
        if [ ! -d .venv ]
        then 
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
        fi
